
# self-defined properties
my:
  name: "V1cent_zZ"
  uuid: ${random.uuid}
  nums:
    - ${random.int}
    - ${random.int[10]} # less than 10
    - ${random.int[10,20]} # range in [10,20]


server:
  port: 8000