#mail properties
mail:
  # simple properties
  host : demo.example.com
  port: 9000
  from: user@demo.example.com
  # list properties
  recipients:
    - admim@demo.example.com
    - owner@demo.example.com
  # Object properties
  credential:
    username: username
    password: password01
    auth-method:
      - SHA1
      - MD5