spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: root
    password: xxx
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate


